import express, { Application } from 'express';
import cors from 'cors';











































































































































































































































































































































































































































































































































































































































































}  }    super.dispose();    _kinAddressController.dispose();    _kinPhoneController.dispose();    _kinRelationshipController.dispose();    _kinNameController.dispose();    _employerController.dispose();    _occupationController.dispose();    _postalCodeController.dispose();    _districtController.dispose();    _cityController.dispose();    _addressController.dispose();    _votersIdController.dispose();    _driversLicenseController.dispose();    _passportController.dispose();    _nationalIdController.dispose();    _lastNameController.dispose();    _middleNameController.dispose();    _firstNameController.dispose();  void dispose() {  @override  }    );            ),              ),                ),                  ],                    SizedBox(height: 16),                    ),                      ),                        child: Text('Save & Continue', style: TextStyle(fontSize: 16)),                        onPressed: _isLoading ? null : _saveProfile,                      child: ElevatedButton(                      height: 50,                      width: double.infinity,                    SizedBox(                    // Save Button                    SizedBox(height: 32),                    ),                      ),                        ),                          ],                            ),                              onChanged: (value) => setState(() => _isPEP = value),                              value: _isPEP,                              subtitle: Text('Government official, senior executive, or close relative/associate'),                              title: Text('I am a Politically Exposed Person (PEP)'),                            SwitchListTile(                          children: [                        child: Column(                        padding: EdgeInsets.all(12),                      child: Padding(                      color: Colors.orange[50],                    Card(                    // PEP Declaration                    SizedBox(height: 24),                    ),                      maxLines: 2,                      ),                        border: OutlineInputBorder(),                        labelText: 'Address',                      decoration: InputDecoration(                      controller: _kinAddressController,                    TextFormField(                                        SizedBox(height: 12),                    ),                      keyboardType: TextInputType.phone,                      ),                        border: OutlineInputBorder(),                        labelText: 'Phone Number',                      decoration: InputDecoration(                      controller: _kinPhoneController,                    TextFormField(                                        SizedBox(height: 12),                    ),                      ),                        border: OutlineInputBorder(),                        labelText: 'Relationship',                      decoration: InputDecoration(                      controller: _kinRelationshipController,                    TextFormField(                                        SizedBox(height: 12),                    ),                      ),                        border: OutlineInputBorder(),                        labelText: 'Full Name',                      decoration: InputDecoration(                      controller: _kinNameController,                    TextFormField(                                        SizedBox(height: 12),                      style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),                    Text('Next of Kin',                     // Next of Kin Section                    SizedBox(height: 24),                    ),                      onChanged: (value) => setState(() => _preferredCommunication = value!),                      ],                        DropdownMenuItem(value: 'assisted', child: Text('Assisted')),                        DropdownMenuItem(value: 'braille', child: Text('Braille')),                        DropdownMenuItem(value: 'sign_language', child: Text('Sign Language')),                        DropdownMenuItem(value: 'text', child: Text('Text')),                        DropdownMenuItem(value: 'voice', child: Text('Voice (Hands-free)')),                      items: [                      ),                        border: OutlineInputBorder(),                        labelText: 'Preferred Communication Method',                      decoration: InputDecoration(                      value: _preferredCommunication,                    DropdownButtonFormField<String>(                    SizedBox(height: 12),                    ],                      ),                        onChanged: (value) => setState(() => _requiresAssistance = value),                        value: _requiresAssistance,                        title: Text('I require assistance'),                      SwitchListTile(                      SizedBox(height: 12),                      ),                        onChanged: (value) => setState(() => _disabilityType = value!),                        ],                          DropdownMenuItem(value: 'other', child: Text('Other')),                          DropdownMenuItem(value: 'multiple', child: Text('Multiple')),                          DropdownMenuItem(value: 'cognitive_disability', child: Text('Cognitive Disability')),                          DropdownMenuItem(value: 'physical_disability', child: Text('Physical Disability')),                          DropdownMenuItem(value: 'hearing_impairment', child: Text('Hearing Impairment')),                          DropdownMenuItem(value: 'visual_impairment', child: Text('Visual Impairment')),                        items: [                        ),                          border: OutlineInputBorder(),                          labelText: 'Type of Disability',                        decoration: InputDecoration(                        value: _disabilityType,                      DropdownButtonFormField<String>(                      SizedBox(height: 12),                    if (_hasDisability) ...[                    ),                      }),                        if (!value) _disabilityType = 'none';                        _hasDisability = value;                      onChanged: (value) => setState(() {                      value: _hasDisability,                      title: Text('I have a disability'),                    SwitchListTile(                                        SizedBox(height: 12),                      style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),                    Text('Accessibility & Support',                     // Accessibility Section                    SizedBox(height: 24),                    ),                      onChanged: (value) => setState(() => _sourceOfFunds = value!),                      ],                        DropdownMenuItem(value: 'other', child: Text('Other')),                        DropdownMenuItem(value: 'government_assistance', child: Text('Government Assistance')),                        DropdownMenuItem(value: 'pension', child: Text('Pension')),                        DropdownMenuItem(value: 'remittances', child: Text('Remittances')),                        DropdownMenuItem(value: 'agriculture', child: Text('Agriculture')),                        DropdownMenuItem(value: 'business', child: Text('Business')),                        DropdownMenuItem(value: 'salary', child: Text('Salary')),                      items: [                      ),                        border: OutlineInputBorder(),                        labelText: 'Source of Funds *',                      decoration: InputDecoration(                      value: _sourceOfFunds,                    DropdownButtonFormField<String>(                    SizedBox(height: 12),                    ),                      onChanged: (value) => setState(() => _incomeRange = value!),                      ],                        DropdownMenuItem(value: 'above_500000', child: Text('Above MKW 500,000')),                        DropdownMenuItem(value: '250000_500000', child: Text('MKW 250,000 - 500,000')),                        DropdownMenuItem(value: '100000_250000', child: Text('MKW 100,000 - 250,000')),                        DropdownMenuItem(value: '50000_100000', child: Text('MKW 50,000 - 100,000')),                        DropdownMenuItem(value: 'below_50000', child: Text('Below MKW 50,000')),                      items: [                      ),                        border: OutlineInputBorder(),                        labelText: 'Monthly Income Range',                      decoration: InputDecoration(                      value: _incomeRange,                    DropdownButtonFormField<String>(                    SizedBox(height: 12),                    ),                      ),                        border: OutlineInputBorder(),                        labelText: 'Employer Name',                      decoration: InputDecoration(                      controller: _employerController,                    TextFormField(                                        SizedBox(height: 12),                    ),                      ),                        border: OutlineInputBorder(),                        labelText: 'Occupation',                      decoration: InputDecoration(                      controller: _occupationController,                    TextFormField(                                        SizedBox(height: 12),                      style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),                    Text('Employment Information',                     // Employment Section                    SizedBox(height: 24),                    ),                      onChanged: (value) => setState(() => _region = value!),                      ],                        DropdownMenuItem(value: 'Southern', child: Text('Southern')),                        DropdownMenuItem(value: 'Central', child: Text('Central')),                        DropdownMenuItem(value: 'Northern', child: Text('Northern')),                      items: [                      ),                        border: OutlineInputBorder(),                        labelText: 'Region *',                      decoration: InputDecoration(                      value: _region,                    DropdownButtonFormField<String>(                    SizedBox(height: 12),                    ),                      validator: (value) => value?.isEmpty ?? true ? 'Required' : null,                      ),                        border: OutlineInputBorder(),                        labelText: 'District *',                      decoration: InputDecoration(                      controller: _districtController,                    TextFormField(                                        SizedBox(height: 12),                    ),                      validator: (value) => value?.isEmpty ?? true ? 'Required' : null,                      ),                        border: OutlineInputBorder(),                        labelText: 'City/Town *',                      decoration: InputDecoration(                      controller: _cityController,                    TextFormField(                                        SizedBox(height: 12),                    ),                      validator: (value) => value?.isEmpty ?? true ? 'Required' : null,                      maxLines: 2,                      ),                        border: OutlineInputBorder(),                        labelText: 'Residential Address *',                      decoration: InputDecoration(                      controller: _addressController,                    TextFormField(                                        SizedBox(height: 12),                      style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),                    Text('Address Information',                     // Address Section                    SizedBox(height: 24),                    ),                      ),                        border: OutlineInputBorder(),                        labelText: 'Voter\'s ID Number',                      decoration: InputDecoration(                      controller: _votersIdController,                    TextFormField(                                        SizedBox(height: 12),                    ),                      ),                        border: OutlineInputBorder(),                        labelText: 'Driver\'s License Number',                      decoration: InputDecoration(                      controller: _driversLicenseController,                    TextFormField(                                        SizedBox(height: 12),                    ),                      ),                        border: OutlineInputBorder(),                        labelText: 'Passport Number',                      decoration: InputDecoration(                      controller: _passportController,                    TextFormField(                                        SizedBox(height: 12),                    ),                      ),                        helperText: 'Format: XXXXX-XX-X',                        border: OutlineInputBorder(),                        labelText: 'National ID Number',                      decoration: InputDecoration(                      controller: _nationalIdController,                    TextFormField(                                        SizedBox(height: 12),                      style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),                    Text('Identification (At least one required)',                     // Identification Section                    SizedBox(height: 24),                    ),                      onChanged: (value) => setState(() => _gender = value!),                      ],                        DropdownMenuItem(value: 'prefer_not_to_say', child: Text('Prefer not to say')),                        DropdownMenuItem(value: 'other', child: Text('Other')),                        DropdownMenuItem(value: 'female', child: Text('Female')),                        DropdownMenuItem(value: 'male', child: Text('Male')),                      items: [                      ),                        border: OutlineInputBorder(),                        labelText: 'Gender *',                      decoration: InputDecoration(                      value: _gender,                    DropdownButtonFormField<String>(                    // Gender                    SizedBox(height: 12),                    ),                      ),                        ),                              : 'Tap to select',                              ? '${_dateOfBirth!.day}/${_dateOfBirth!.month}/${_dateOfBirth!.year}'                          _dateOfBirth != null                        child: Text(                        ),                          border: OutlineInputBorder(),                          labelText: 'Date of Birth *',                        decoration: InputDecoration(                      child: InputDecorator(                      onTap: _selectDate,                    InkWell(                    // Date of Birth                    SizedBox(height: 12),                    ),                      validator: (value) => value?.isEmpty ?? true ? 'Required' : null,                      ),                        border: OutlineInputBorder(),                        labelText: 'Last Name *',                      decoration: InputDecoration(                      controller: _lastNameController,                    TextFormField(                                        SizedBox(height: 12),                    ),                      ),                        border: OutlineInputBorder(),                        labelText: 'Middle Name',                      decoration: InputDecoration(                      controller: _middleNameController,                    TextFormField(                                        SizedBox(height: 12),                    ),                      validator: (value) => value?.isEmpty ?? true ? 'Required' : null,                      ),                        border: OutlineInputBorder(),                        labelText: 'First Name *',                      decoration: InputDecoration(                      controller: _firstNameController,                    TextFormField(                                        SizedBox(height: 12),                      style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),                    Text('Personal Information',                     // Personal Information Section                    SizedBox(height: 24),                    ),                      ),                        ),                          ],                            ),                              style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),                              'Required by Reserve Bank of Malawi',                            Text(                            SizedBox(height: 8),                            ),                              textAlign: TextAlign.center,                              style: TextStyle(fontSize: 14),                              'Complete your KYC verification to unlock full wallet features',                            Text(                            SizedBox(height: 8),                            Icon(Icons.info, color: Colors.blue, size: 40),                          children: [                        child: Column(                        padding: EdgeInsets.all(16),                      child: Padding(                      color: Colors.blue[50],                    Card(                    // Info Card                  children: [                  crossAxisAlignment: CrossAxisAlignment.start,                child: Column(                key: _formKey,              child: Form(              padding: EdgeInsets.all(16),          : SingleChildScrollView(          ? Center(child: CircularProgressIndicator())      body: _isLoading      ),        backgroundColor: Theme.of(context).primaryColor,        title: Text('KYC Profile'),      appBar: AppBar(    return Scaffold(  Widget build(BuildContext context) {  @override  }    }      setState(() => _dateOfBirth = picked);    if (picked != null) {    );      helpText: 'Select Date of Birth (Must be 18+)',      lastDate: DateTime.now().subtract(Duration(days: 365 * 18)),      firstDate: DateTime(1920),      initialDate: _dateOfBirth ?? DateTime(1990),      context: context,    final picked = await showDatePicker(  Future<void> _selectDate() async {  }    }      setState(() => _isLoading = false);    } finally {      );        type: 'error',        message: 'An error occurred while saving profile',        title: 'Error',      await _notifications.addNotification(    } catch (e) {      }        );          type: 'error',          message: error['message'] ?? 'Failed to save profile',          title: 'Save Failed',        await _notifications.addNotification(        final error = json.decode(response.body);      } else {        Navigator.pushReplacementNamed(context, '/kyc-documents');                );          type: 'success',          message: 'KYC profile saved successfully. Next, upload your documents.',          title: 'Profile Saved',        await _notifications.addNotification(      if (response.statusCode == 200) {      );        }),          'pep_status': _isPEP,          'next_of_kin_address': _kinAddressController.text,          'next_of_kin_phone': _kinPhoneController.text,          'next_of_kin_relationship': _kinRelationshipController.text,          'next_of_kin_name': _kinNameController.text,          'preferred_communication': _preferredCommunication,          'requires_assistance': _requiresAssistance,          'disability_type': _disabilityType,          'has_disability': _hasDisability,          'source_of_funds': _sourceOfFunds,          'monthly_income_range': _incomeRange,          'employer_name': _employerController.text,          'occupation': _occupationController.text,          'postal_code': _postalCodeController.text,          'region': _region,          'district': _districtController.text,          'city': _cityController.text,          'residential_address': _addressController.text,          'voters_id': _votersIdController.text.isNotEmpty ? _votersIdController.text : null,          'drivers_license': _driversLicenseController.text.isNotEmpty ? _driversLicenseController.text : null,          'passport_number': _passportController.text.isNotEmpty ? _passportController.text : null,          'national_id': _nationalIdController.text.isNotEmpty ? _nationalIdController.text : null,          'nationality': _nationality,          'gender': _gender,          'date_of_birth': _dateOfBirth?.toIso8601String().split('T')[0],          'last_name': _lastNameController.text,          'middle_name': _middleNameController.text,          'first_name': _firstNameController.text,        body: json.encode({        },          'Content-Type': 'application/json',          'Authorization': 'Bearer $token',        headers: {        Uri.parse('http://localhost:3000/api/kyc/profile'),      final response = await http.post(      final token = prefs.getString('token');      final prefs = await SharedPreferences.getInstance();    try {    setState(() => _isLoading = true);    }      return;      );        type: 'error',        message: 'Please provide at least one form of identification',        title: 'ID Required',      await _notifications.addNotification(        _votersIdController.text.isEmpty) {        _driversLicenseController.text.isEmpty &&        _passportController.text.isEmpty &&    if (_nationalIdController.text.isEmpty &&    // Validate at least one ID    }      return;      );        type: 'error',        message: 'Please fill in all required fields',        title: 'Form Incomplete',      await _notifications.addNotification(    if (!_formKey.currentState!.validate()) {  Future<void> _saveProfile() async {  }    }      setState(() => _isLoading = false);    } finally {      print('Error loading profile: $e');    } catch (e) {      }        });          _isPEP = profile['pep_status'] ?? false;          _kinAddressController.text = profile['next_of_kin_address'] ?? '';          _kinPhoneController.text = profile['next_of_kin_phone'] ?? '';          _kinRelationshipController.text = profile['next_of_kin_relationship'] ?? '';          _kinNameController.text = profile['next_of_kin_name'] ?? '';          _preferredCommunication = profile['preferred_communication'] ?? 'voice';          _requiresAssistance = profile['requires_assistance'] ?? false;          _disabilityType = profile['disability_type'] ?? 'none';          _hasDisability = profile['has_disability'] ?? false;          _sourceOfFunds = profile['source_of_funds'] ?? 'salary';          _incomeRange = profile['monthly_income_range'] ?? 'below_50000';          _employerController.text = profile['employer_name'] ?? '';          _occupationController.text = profile['occupation'] ?? '';          _postalCodeController.text = profile['postal_code'] ?? '';          _region = profile['region'] ?? 'Central';          _districtController.text = profile['district'] ?? '';          _cityController.text = profile['city'] ?? '';          _addressController.text = profile['residential_address'] ?? '';          _votersIdController.text = profile['voters_id'] ?? '';          _driversLicenseController.text = profile['drivers_license'] ?? '';          _passportController.text = profile['passport_number'] ?? '';          _nationalIdController.text = profile['national_id'] ?? '';          _nationality = profile['nationality'] ?? 'Malawian';          _gender = profile['gender'] ?? 'male';        setState(() {                }          _dateOfBirth = DateTime.parse(profile['date_of_birth']);        if (profile['date_of_birth'] != null) {                _lastNameController.text = profile['last_name'] ?? '';        _middleNameController.text = profile['middle_name'] ?? '';        _firstNameController.text = profile['first_name'] ?? '';        // Populate fields with existing data                final profile = json.decode(response.body);      if (response.statusCode == 200) {      );        headers: {'Authorization': 'Bearer $token'},        Uri.parse('http://localhost:3000/api/kyc/profile'),      final response = await http.get(            final token = prefs.getString('token');      final prefs = await SharedPreferences.getInstance();    try {        setState(() => _isLoading = true);  Future<void> _loadExistingProfile() async {  }    _loadExistingProfile();    super.initState();  void initState() {  @override  bool _isPEP = false;  // PEP Status  final TextEditingController _kinAddressController = TextEditingController();  final TextEditingController _kinPhoneController = TextEditingController();  final TextEditingController _kinRelationshipController = TextEditingController();  final TextEditingController _kinNameController = TextEditingController();  // Next of Kin  String _preferredCommunication = 'voice';  bool _requiresAssistance = false;  String _disabilityType = 'none';  bool _hasDisability = false;  // Disability & Accessibility  String _sourceOfFunds = 'salary';  String _incomeRange = 'below_50000';  final TextEditingController _employerController = TextEditingController();  final TextEditingController _occupationController = TextEditingController();  // Employment  final TextEditingController _postalCodeController = TextEditingController();  String _region = 'Central';  final TextEditingController _districtController = TextEditingController();  final TextEditingController _cityController = TextEditingController();  final TextEditingController _addressController = TextEditingController();  // Address  final TextEditingController _votersIdController = TextEditingController();  final TextEditingController _driversLicenseController = TextEditingController();  final TextEditingController _passportController = TextEditingController();  final TextEditingController _nationalIdController = TextEditingController();  // Identification  String _nationality = 'Malawian';  String _gender = 'male';  DateTime? _dateOfBirth;  final TextEditingController _lastNameController = TextEditingController();  final TextEditingController _middleNameController = TextEditingController();  final TextEditingController _firstNameController = TextEditingController();  // Personal Information  bool _isLoading = false;  final NotificationService _notifications = NotificationService();  final _formKey = GlobalKey<FormState>();class _KycProfileScreenState extends State<KycProfileScreen> {}  _KycProfileScreenState createState() => _KycProfileScreenState();  @override  const KycProfileScreen({Key? key}) : super(key: key);class KycProfileScreen extends StatefulWidget {import '../services/notification_service.dart';import 'package:shared_preferences/shared_preferences.dart';import 'dart:convert';import helmet from 'helmet';
import morgan from 'morgan';
import dotenv from 'dotenv';
import { WebSocketServer } from 'ws';
import { createServer } from 'http';
import authRoutes from './routes/auth.routes';
import userRoutes from './routes/user.routes';
import transactionRoutes from './routes/transaction.routes';
import walletRoutes from './routes/wallet.routes';
import voiceRoutes from './routes/voice.routes';
import adminRoutes from './routes/admin.routes';
import moneyRequestRoutes from './routes/money-request.routes';
import servicesRoutes from './routes/services.routes';
import qrRoutes from './routes/qr.routes';
import creditRoutes from './routes/credit.routes';
import bnplRoutes from './routes/bnpl.routes';
import kycRoutes from './routes/kyc.routes';
import { SpeechmaticsProxyService } from './services/speechmatics-proxy.service';

dotenv.config();

const app: Application = express();
const PORT = process.env.PORT || 3000;

// Create HTTP server for both Express and WebSocket
const server = createServer(app);

// Middleware
app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(morgan('dev'));

// Routes
app.use('/api/auth', authRoutes);
app.use('/api/users', userRoutes);
app.use('/api/transactions', transactionRoutes);
app.use('/api/wallet', walletRoutes);
app.use('/api/voice', voiceRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/money-requests', moneyRequestRoutes);
app.use('/api/services', servicesRoutes);
app.use('/api/qr', qrRoutes);
app.use('/api/credit', creditRoutes);
app.use('/api/bnpl', bnplRoutes);
app.use('/api/kyc', kycRoutes);

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'OK', message: 'InkaWallet API is running' });
});

// Initialize Speechmatics WebSocket proxy
const speechmaticsProxy = new SpeechmaticsProxyService();
const wss = new WebSocketServer({ server, path: '/ws/voice' });

wss.on('connection', (ws, req) => {
  speechmaticsProxy.handleConnection(ws, req);
});

// Start server
server.listen(PORT, () => {
  console.log(`🚀 InkaWallet API running on port ${PORT}`);
  console.log(`📱 Environment: ${process.env.NODE_ENV}`);
  console.log(`🎤 WebSocket Voice Proxy: ws://localhost:${PORT}/ws/voice`);
  console.log(`🔑 Speechmatics API Key: ${speechmaticsProxy.getMaskedApiKey()}`);
});

export default app;
